name: AWS deploy workflow

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_default_region:
        required: true

jobs:
  aws-deploy:
    name: AWS deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_default_region }}

      # sam build
      - run: sam build --use-container

      # sam deploy (To run this, you must have created an S3 bucket)
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ inputs.stage }}-mutual-authentication-stack --s3-bucket ${{ inputs.stage }}-mutual-authentication-api --capabilities CAPABILITY_IAM --region ${{ secrets.aws_default_region }}
