name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-workflow-aws-deply:
    uses: ./.github/workflows/aws-deploy.yml
    with:
      stage: production
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_default_region: sa-east-1
